#Name: Kelechi Ogudu
#USC_ID: 5413285132

CXX = g++
CXXFLAGS = -ggdb -Wall
OBJS = FindShortestPath.o BellManFordImp.o

FindShortestPath: $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@

FindShortestPath.o: BellManFordImp.h
BellManFordImp.o: BellManFordImp.h
